apiVersion: v1
kind: Service
metadata:
  name: cluster-mongodb
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: cluster-mongodb
