{{- if .Values.grafanaLokiSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-loki-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.grafanaLokiSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}