apiVersion: v1
kind: Secret
metadata:
  name: {{ (first .Values.imagePullSecrets).name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
