apiVersion: v1
kind: Service
metadata:
  name: pubsub-redis
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: pubsub-redis
