{{- if .Values.images.silohost.metricsServerPort }}
apiVersion: v1
kind: Service
metadata:
  name: silohost-metrics
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
    prometheus-metrics-server: "true"
spec:
  ports:
    - name: metrics
      port: {{ .Values.images.silohost.metricsServerPort }}
      targetPort: {{ .Values.images.silohost.metricsServerPort }}
  selector:
    app: silohost
{{- end }}