{{- if .Values.images.silohost.minesweeperRngSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: minesweeper-rng-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
type: Opaque
data:
  MINESWEEPER_RNG_SECRET: {{ .Values.images.silohost.minesweeperRngSecret | b64enc }}
{{- end }}