apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    {{- include "infinite-checkboxes.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp
